from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field


class EventType(StrEnum):
    SYSTEM_HEARTBEAT = "SYSTEM_HEARTBEAT"
    HOST_UPDATED = "HOST_UPDATED"
    DOCKER_INVENTORY_UPDATED = "DOCKER_INVENTORY_UPDATED"
    HEALTH_STATE_CHANGED = "HEALTH_STATE_CHANGED"
    SERVER_CONNECTED = "SERVER_CONNECTED"
    SERVER_DISCONNECTED = "SERVER_DISCONNECTED"
    TOPOLOGY_UPDATED = "TOPOLOGY_UPDATED"
    NODE_STATE_CHANGED = "NODE_STATE_CHANGED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    INCIDENT_UPDATED = "INCIDENT_UPDATED"
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    OBSERVATION_ADDED = "OBSERVATION_ADDED"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    HYPOTHESIS_UPDATED = "HYPOTHESIS_UPDATED"
    HYPOTHESIS_DISPROVED = "HYPOTHESIS_DISPROVED"
    ROOT_CAUSE_CONFIRMED = "ROOT_CAUSE_CONFIRMED"
    INVESTIGATION_INCOMPLETE = "INVESTIGATION_INCOMPLETE"
    INVESTIGATION_FAILED = "INVESTIGATION_FAILED"
    REPAIR_PLANNED = "REPAIR_PLANNED"
    POLICY_DECIDED = "POLICY_DECIDED"
    APPROVAL_REQUIRED = "APPROVAL_REQUIRED"
    APPROVAL_UPDATED = "APPROVAL_UPDATED"
    ACTION_STARTED = "ACTION_STARTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_CHECK_COMPLETED = "VERIFICATION_CHECK_COMPLETED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    ROLLBACK_STARTED = "ROLLBACK_STARTED"
    ROLLBACK_COMPLETED = "ROLLBACK_COMPLETED"
    REPAIR_EXECUTION_STARTED = "REPAIR_EXECUTION_STARTED"
    REPAIR_EXECUTION_COMPLETED = "REPAIR_EXECUTION_COMPLETED"
    REPAIR_EXECUTION_FAILED = "REPAIR_EXECUTION_FAILED"
    CHAOS_INJECTED = "CHAOS_INJECTED"
    CHAOS_RESET = "CHAOS_RESET"


class RealtimeEvent(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid4()))
    type: EventType = EventType.SYSTEM_HEARTBEAT
    timestamp: datetime = Field(default_factory=lambda: datetime.now(UTC))
    server_id: str | None = None
    incident_id: str | None = None
    resource_id: str | None = None
    payload: dict[str, Any] = Field(default_factory=dict)
