'use client';
import {useState} from 'react';
import {Check,Trash2} from 'lucide-react';
import {api,useData,label} from '@/lib/client';

type ActionPlan={id:string;version:number;status:string;action:string;target_kind:string;target_name:string;project_name:string|null;detail:string|null;policy_reason:string;requires_exact_confirmation:boolean};
export function DokployActions(){const actions=useData<ActionPlan[]>('dokploy/actions');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[confirmation,setConfirmation]=useState<Record<string,string>>({});
 async function decide(plan:ActionPlan,decision:'APPROVED'|'REJECTED'){setBusy(true);setError('');try{await api(`dokploy/actions/${plan.id}/approval`,{version:plan.version,decision,confirmation:confirmation[plan.id]||null});await actions.refresh();}catch(e){setError(e instanceof Error?e.message:'Could not record action decision');}finally{setBusy(false);}}
 async function remove(plan:ActionPlan){setBusy(true);try{await api(`dokploy/actions/${plan.id}`,undefined,'DELETE');await actions.refresh();}catch(e){setError(e instanceof Error?e.message:'Could not delete action plan');}finally{setBusy(false);}}
 if(!actions.data?.length&&!actions.loading)return null;
 return <section className="deployment-list"><h2>Dokploy operations</h2>{error&&<p className="error-notice">{error}</p>}{actions.data?.map(plan=><section className="panel deployment-plan" key={plan.id}><div className="panel-heading"><div><Check size={19}/><h2>{label(plan.action)} {plan.target_kind}</h2></div><span className="pill">{label(plan.status)}</span></div><div className="panel-body"><dl className="plan-fields"><dt>Target</dt><dd>{plan.target_name}</dd><dt>Project</dt><dd>{plan.project_name||'—'}</dd><dt>Version</dt><dd>{plan.version}</dd></dl><p>{plan.policy_reason}</p>{plan.detail&&<div className="notice">{label(plan.status)} — {plan.detail}</div>}{plan.status==='AWAITING_APPROVAL'&&<div className="actions">{plan.requires_exact_confirmation&&<label>Type <strong>{plan.target_name}</strong> to delete<input value={confirmation[plan.id]||''} onChange={e=>setConfirmation({...confirmation,[plan.id]:e.target.value})}/></label>}<button className="button primary" disabled={busy||(plan.requires_exact_confirmation&&confirmation[plan.id]!==plan.target_name)} onClick={()=>void decide(plan,'APPROVED')}>Approve version {plan.version}</button><button className="button" disabled={busy} onClick={()=>void decide(plan,'REJECTED')}>Reject</button></div>}{['VERIFIED','FAILED','REJECTED'].includes(plan.status)&&<div className="actions"><button className="button danger" disabled={busy} onClick={()=>void remove(plan)}><Trash2 size={14}/>Delete plan</button></div>}</div></section>)}</section>;
}
