'use client';
import {useMemo,useState} from 'react';
import {Activity,Database,Zap} from 'lucide-react';
import {formatBytes,formatPercent,timeAgo,useData} from '@/lib/client';
import type {Resource,TelemetrySeries} from '@/lib/types';

const ranges=['1h','24h','7d','30d'] as const;
function Sparkline({values}:{values:(number|null)[]}){const path=useMemo(()=>{const usable=values.map((value,index)=>({value,index})).filter((item):item is {value:number;index:number}=>item.value!==null);if(usable.length<2)return '';const max=Math.max(...usable.map(item=>item.value)),min=Math.min(...usable.map(item=>item.value)),span=max-min||1;return usable.map((item,index)=>`${index?'L':'M'} ${(item.index/(values.length-1))*260} ${54-((item.value-min)/span)*46}`).join(' ');},[values]);return <svg className="metric-spark" viewBox="0 0 260 60" role="img" aria-label="Historical metric trend">{path?<><path className="spark-fill" d={`${path} L 260 60 L 0 60 Z`}/><path className="spark-line" d={path}/></>:<text x="130" y="34" textAnchor="middle">History unavailable</text>}</svg>;}
export function TelemetryPanel({resource}:{resource:Resource}){const[range,setRange]=useState<(typeof ranges)[number]>('24h');const path=`telemetry/resource?resource_id=${encodeURIComponent(resource.id)}&range=${range}`;const{data,error,loading}=useData<TelemetrySeries>(path);const cpu=data?.points.map(point=>point.cpu_percent)??[];return <div className="detail-section telemetry-section"><div className="section-heading"><h3>Live telemetry</h3><span className="source-freshness">{resource.metrics?.source||'No source'} · {timeAgo(resource.metrics?.observed_at)}</span></div><div className="metric-grid"><div><Activity size={14}/><span>CPU</span><strong>{formatPercent(resource.metrics?.cpu_percent)}</strong></div><div><Database size={14}/><span>Memory</span><strong>{formatBytes(resource.metrics?.memory_used_bytes)}</strong><small>{formatPercent(resource.metrics?.memory_percent)}</small></div><div><Zap size={14}/><span>Network</span><strong>{formatBytes(resource.metrics?.network_rx_bytes)}</strong><small>{resource.metrics?.source==='beszel'?'current traffic':'received'}</small></div></div><div className="history-head"><span>CPU history</span><div className="range-switch">{ranges.map(value=><button key={value} className={range===value?'active':''} onClick={()=>setRange(value)}>{value}</button>)}</div></div>{loading?<div className="spark-loading"/>:<Sparkline values={cpu}/>}<small className="telemetry-note">{error||data?.message||`${data?.points.length??0} Beszel samples`}</small></div>;}
