'use client';
import {Suspense,useEffect,useMemo,useRef} from 'react';
import {Canvas,useThree} from '@react-three/fiber';
import {ContactShadows,Html,Line,OrbitControls,RoundedBox,useTexture} from '@react-three/drei';
import * as THREE from 'three';
import type {OrbitControls as OrbitType} from 'three-stdlib';
import type {Connection,Project,Resource} from '@/lib/types';
import {color} from '@/lib/client';
import {worldGraph,type SceneNode} from '@/lib/world-layout';

type WorldTextures={rock:THREE.Texture;ground:THREE.Texture;concrete:THREE.Texture;road:THREE.Texture};
function random(seed:number){return()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};}
function useWorldTextures():WorldTextures{const maps=useTexture(['/textures/rock.svg','/textures/ground.svg','/textures/concrete.svg','/textures/road.svg']);useEffect(()=>{maps.forEach((map,index)=>{map.wrapS=map.wrapT=THREE.RepeatWrapping;map.repeat.set(index===0?2:3,index===0?3:3);map.colorSpace=THREE.SRGBColorSpace;map.anisotropy=4;map.needsUpdate=true;});},[maps]);return{rock:maps[0],ground:maps[1],concrete:maps[2],road:maps[3]};}
function Rock({seed,texture}:{seed:number;texture:THREE.Texture}){const geometry=useMemo(()=>{const rand=random(seed+1);const geom=new THREE.CylinderGeometry(3.85,.75,3.6,14,5);const pos=geom.attributes.position;for(let i=0;i<pos.count;i++){const y=pos.getY(i),falloff=1-Math.max(0,-y)/5;pos.setXYZ(i,pos.getX(i)+(rand()-.5)*.58*falloff,y+(rand()-.5)*.32,pos.getZ(i)+(rand()-.5)*.58*falloff);}geom.computeVertexNormals();return geom;},[seed]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <group><mesh geometry={geometry} position={[0,-2.15,0]} castShadow receiveShadow><meshStandardMaterial map={texture} color="#51615c" roughness={.88} metalness={.05}/></mesh><mesh position={[0,-4.15,0]} rotation={[0,seed*.01,0]} castShadow><coneGeometry args={[1.12,2.1,7]}/><meshStandardMaterial map={texture} color="#293735" roughness={1}/></mesh></group>;}
function Tree({position,scale=1}:{position:[number,number,number];scale?:number}){return <group position={position} scale={scale}><mesh position={[0,.3,0]} castShadow><cylinderGeometry args={[.06,.12,.62,6]}/><meshStandardMaterial color="#6a5d49" roughness={1}/></mesh><mesh position={[0,.79,0]} castShadow><coneGeometry args={[.43,1.15,7]}/><meshStandardMaterial color="#2e6148" roughness={.94} flatShading/></mesh><mesh position={[0,1.18,0]} castShadow><coneGeometry args={[.32,.82,7]}/><meshStandardMaterial color="#4d8a61" roughness={.9} flatShading/></mesh></group>;}
function Building({resource,index,onSelect,selected,texture}:{resource:Resource;index:number;onSelect:(resource:Resource)=>void;selected:boolean;texture:THREE.Texture}){const database=['postgres','mysql','mariadb','mongo','redis','libsql'].includes(resource.kind);const hue=color(resource.health);const height=database?1.25:1.08+(index%3)*.32;return <group onClick={event=>{event.stopPropagation();onSelect(resource);}} onPointerOver={event=>{event.stopPropagation();document.body.style.cursor='pointer';}} onPointerOut={()=>document.body.style.cursor='auto'}>
 {database?<><mesh position={[0,height/2+.15,0]} castShadow><cylinderGeometry args={[.52,.52,height,24]}/><meshStandardMaterial map={texture} color={selected?'#9eaaa7':'#667875'} metalness={.58} roughness={.32}/></mesh>{[.23,.67,1.1].map(y=><mesh key={y} position={[0,y,0]}><cylinderGeometry args={[.55,.55,.055,24]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={.8}/></mesh>)}</>:<><RoundedBox args={[1.12,height,1.18]} position={[0,height/2+.15,0]} radius={.045} castShadow receiveShadow><meshStandardMaterial map={texture} color={selected?'#c0cbc8':'#899895'} metalness={.23} roughness={.6}/></RoundedBox><mesh position={[0,height+.18,0]} castShadow><boxGeometry args={[1.22,.11,1.28]}/><meshStandardMaterial color="#b4bfbb" roughness={.5}/></mesh><mesh position={[.1,height+.34,.12]} castShadow><boxGeometry args={[.42,.24,.52]}/><meshStandardMaterial color="#43524f" metalness={.3}/></mesh>{[0,1,2].map(row=><group key={row}>{[-.34,0,.34].map(x=><mesh key={x} position={[x,.37+row*.28,.595]}><planeGeometry args={[.15,.14]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={selected?1.2:.45}/></mesh>)}</group>)}</>}
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.075,0]}><ringGeometry args={[.77,.84,40]}/><meshBasicMaterial color={selected?'#e4fff2':hue} transparent opacity={selected?1:.65}/></mesh><pointLight color={hue} intensity={selected?.75:.22} distance={3}/>
 </group>;}
function Debris({seed}:{seed:number}){const items=useMemo(()=>{const rand=random(seed+90);return Array.from({length:5},()=>({position:[(rand()-.5)*9,-2-rand()*4,(rand()-.5)*9] as [number,number,number],scale:.12+rand()*.28,rotation:[rand()*3,rand()*3,rand()*3] as [number,number,number]}));},[seed]);return <>{items.map((item,index)=><mesh key={index} {...item}><dodecahedronGeometry args={[1,0]}/><meshStandardMaterial color="#263330" roughness={1}/></mesh>)}</>;}
function Island({project,position,selected,onSelect,domains,textures}:{project:Project;position:[number,number,number];selected:string|null;onSelect:(value:Resource|Project)=>void;domains:boolean;textures:WorldTextures}){const seed=project.id.split('').reduce((sum,char)=>sum+char.charCodeAt(0),0);const trees=useMemo(()=>{const rand=random(seed);return Array.from({length:14},(_,tree)=>{const angle=tree/14*Math.PI*2+rand()*.35;return{position:[Math.cos(angle)*(2.8+rand()*.45),.1,Math.sin(angle)*(2.8+rand()*.45)] as [number,number,number],scale:.38+rand()*.48};});},[seed]);const resources=project.resources.slice(0,8);const hue=color(project.health);return <group position={position}>
 <Rock seed={seed} texture={textures.rock}/><Debris seed={seed}/><mesh position={[0,-.12,0]} receiveShadow castShadow><cylinderGeometry args={[3.72,3.86,.42,14]}/><meshStandardMaterial map={textures.ground} color="#6e846d" roughness={.94}/></mesh><mesh position={[0,-.37,0]}><cylinderGeometry args={[3.82,3.82,.055,14]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={.9}/></mesh>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.082,0]} receiveShadow><planeGeometry args={[5.35,.62]}/><meshStandardMaterial map={textures.road} roughness={.88}/></mesh><mesh rotation={[-Math.PI/2,0,Math.PI/2]} position={[0,.083,0]} receiveShadow><planeGeometry args={[5.35,.55]}/><meshStandardMaterial map={textures.road} roughness={.88}/></mesh>
 {trees.map((tree,treeIndex)=><Tree key={treeIndex} {...tree}/>)}
 {resources.map((resource,resourceIndex)=>{const columns=Math.min(3,resources.length),x=(resourceIndex%columns-(columns-1)/2)*1.5,z=(Math.floor(resourceIndex/columns)-.5)*1.8;return <group key={resource.id} position={[x,0,z]}><Building resource={resource} index={resourceIndex} selected={selected===resource.id} onSelect={onSelect} texture={textures.concrete}/>{selected===resource.id?<Html position={[0,2,0]} center distanceFactor={30} zIndexRange={[20,0]}><button className="building-label" onClick={()=>onSelect(resource)}>{resource.name}</button></Html>:null}</group>;})}
 {!resources.length?<mesh position={[0,.3,0]}><boxGeometry args={[1.2,.3,1.2]}/><meshStandardMaterial color="#6f7a78" wireframe/></mesh>:null}
 <Html center position={[0,2.7,-1.9]} distanceFactor={32} zIndexRange={[15,0]}><button className={`island-label ${selected===project.id?'selected':''}`} onClick={()=>onSelect(project)}><i style={{background:hue}}/><span>{project.name}<small>{project.resources.length} {project.resources.length===1?'service':'services'}{domains&&project.resources.flatMap(resource=>resource.domains).length?` · ${project.resources.flatMap(resource=>resource.domains).length} domains`:''}</small></span></button></Html>
 {domains&&project.resources.some(resource=>resource.domains.length>0)?<group position={[2.8,0,.7]}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.11,0]}><torusGeometry args={[.4,.045,8,32]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={1.2}/></mesh><Line points={[[0,.2,0],[-.5,.8,-.3],[-1.3,.45,-.7]]} color={hue} lineWidth={2} transparent opacity={.85}/></group>:null}
 </group>;}
function Gateway({node}:{node:SceneNode}){const domain=node.kind==='domain',accent=domain?'#6ff2c6':'#9cb9ff';return <group position={node.point}><mesh position={[0,.55,0]} rotation={[0,Math.PI/4,0]}><octahedronGeometry args={[domain?.7:.9,0]}/><meshStandardMaterial color={accent} emissive={accent} emissiveIntensity={1.1} metalness={.45} roughness={.3}/></mesh><mesh position={[0,.1,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[.82,1.02,32]}/><meshBasicMaterial color={accent} transparent opacity={.8}/></mesh><pointLight color={accent} intensity={.8} distance={5}/><Html center position={[0,1.65,0]} distanceFactor={34} zIndexRange={[14,0]}><div className="gateway-label"><small>{domain?'Domain gateway':'Network hub'}</small>{node.label}</div></Html></group>;}
function Camera({reset,focus,projects,positions}:{reset:number;focus:string|null;projects:Project[];positions:Map<string,[number,number,number]>}){const ref=useRef<OrbitType>(null);const{camera,invalidate}=useThree();const projectsRef=useRef(projects);const positionsRef=useRef(positions);projectsRef.current=projects;positionsRef.current=positions;useEffect(()=>{const currentProjects=projectsRef.current,target=currentProjects.find(project=>project.id===focus||project.resources.some(resource=>resource.id===focus)),point=target?positionsRef.current.get(target.id)||[0,0,0]:[0,0,0],distance=target?12:Math.max(25,Math.sqrt(currentProjects.length)*12);camera.position.set(point[0]+distance*.7,distance*.85,point[2]+distance);ref.current?.target.set(point[0],0,point[2]);ref.current?.update();invalidate();},[reset,focus,camera,invalidate]);return <OrbitControls ref={ref} makeDefault enableDamping dampingFactor={.12} minDistance={6} maxDistance={100} maxPolarAngle={Math.PI/2.2} minPolarAngle={.15}/>;}
function WorldContent({projects,graph,selected,onSelect,domains}:{projects:Project[];graph:ReturnType<typeof worldGraph>;selected:string|null;onSelect:(value:Resource|Project)=>void;domains:boolean}){const textures=useWorldTextures();return <>{projects.map(project=><Island key={project.id} project={project} position={graph.positions.get(project.id)||[0,0,0]} selected={selected} onSelect={onSelect} domains={domains} textures={textures}/>)}{graph.nodes.filter(node=>node.kind!=='project').map(node=><Gateway key={node.id} node={node}/>)}{graph.edges.map(edge=>{const from:[number,number,number]=[edge.from[0],.38,edge.from[2]],to:[number,number,number]=[edge.to[0],.38,edge.to[2]],mid:[number,number,number]=[(from[0]+to[0])/2,edge.kind==='DEPENDS_ON'?1.2:.85,(from[2]+to[2])/2];const accent=edge.kind==='DEPENDS_ON'?'#9cb9ff':edge.kind==='ROUTES_TO'?'#6ff2c6':'#77e8c4';return <group key={edge.id}><Line points={[from,mid,to]} color={accent} lineWidth={3} transparent opacity={.25}/><Line points={[from,mid,to]} color={accent} lineWidth={1} dashed dashSize={.42} gapSize={.18} transparent opacity={.9}/></group>;})}</>;}
export default function WorldScene({projects,connections,selected,onSelect,reset,focus,domains,networks}:{projects:Project[];connections:Connection[];selected:string|null;onSelect:(value:Resource|Project)=>void;reset:number;focus:string|null;domains:boolean;networks:boolean}){const graph=useMemo(()=>worldGraph(projects,domains?connections:connections.filter(connection=>connection.kind!=='ROUTES_TO'),networks),[projects,connections,domains,networks]);return <Canvas shadows dpr={[1,1.5]} frameloop="demand" camera={{position:[20,25,32],fov:42,near:.1,far:180}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} onCreated={({gl})=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.22;gl.outputColorSpace=THREE.SRGBColorSpace;}}><fog attach="fog" args={['#0c1316',42,105]}/><ambientLight intensity={.4}/><hemisphereLight args={['#bedfe3','#101e17',1.05]}/><directionalLight position={[10,20,10]} intensity={2.8} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-30} shadow-camera-right={30} shadow-camera-top={30} shadow-camera-bottom={-30} shadow-bias={-.001}/><directionalLight position={[-15,9,-15]} color="#67b69e" intensity={1.5}/><pointLight position={[0,4,0]} color="#8cffd1" intensity={1.3} distance={28}/><Suspense fallback={null}><WorldContent projects={projects} graph={graph} selected={selected} onSelect={onSelect} domains={domains}/><ContactShadows position={[0,-5.2,0]} opacity={.34} scale={110} blur={3.5} far={15} resolution={256} frames={1}/></Suspense><Camera reset={reset} focus={focus} projects={projects} positions={graph.positions}/></Canvas>;}
