'use client';
import dynamic from 'next/dynamic';import Link from 'next/link';import {Component,useEffect,useMemo,useState} from 'react';
import {Search,RefreshCw,Maximize,RotateCcw,Layers3,Globe2,MousePointer2,X,Sparkles,ArrowRight,Network,Box,ChevronRight,Focus,Info,Cpu,MemoryStick,HardDrive,GitBranch,Clock3} from 'lucide-react';
import {useData,timeAgo,label,formatPercent} from '@/lib/client';import type {World,Resource,Project} from '@/lib/types';import {Heading,Status,Empty,Loading,ErrorNotice,External} from './ui';import {TelemetryPanel} from './telemetry-panel';
const Scene=dynamic(()=>import('./world-scene'),{ssr:false,loading:()=> <Loading/>});
class SceneBoundary extends Component<{children:React.ReactNode;use2d:()=>void},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<Empty title="3D world could not load"><span>The world stayed here so you can retry it or choose the 2D map.</span><span className="scene-recovery"><button className="button primary" onClick={()=>this.setState({failed:false})}>Retry 3D</button><button className="button" onClick={this.props.use2d}>Use 2D</button></span></Empty>:this.props.children;}}
export function WorldPage(){const{data,error,loading,refresh}=useData<World>('world');const[query,setQuery]=useState(''),[health,setHealth]=useState('all'),[projectFilter,setProjectFilter]=useState('all'),[mode,setMode]=useState<'3d'|'2d'>('3d'),[selected,setSelected]=useState<string|null>(null),[focus,setFocus]=useState<string|null>(null),[reset,setReset]=useState(0),[domains,setDomains]=useState(true),[networks,setNetworks]=useState(false);
 useEffect(()=>{const canvas=document.createElement('canvas');if(window.matchMedia('(max-width: 760px), (prefers-reduced-motion: reduce)').matches||!canvas.getContext('webgl2'))queueMicrotask(()=>setMode('2d'));},[]);
 const projects=useMemo(()=>data?.projects.filter(p=>(projectFilter==='all'||p.id===projectFilter)&&(health==='all'||p.health===health)&&(!query||[p.name,...p.resources.flatMap(r=>[r.name,...r.domains.map(d=>d.url)])].some(v=>v.toLowerCase().includes(query.toLowerCase()))))||[],[data,projectFilter,health,query]);
 const selectedProject=data?.projects.find(p=>p.id===selected||p.resources.some(r=>r.id===selected));const resource=selectedProject?.resources.find(r=>r.id===selected);const active=resource||selectedProject;const count=data?.projects.reduce((a,p)=>a+p.resources.length,0)||0;const attention=data?.projects.filter(p=>['UNHEALTHY','DEGRADED'].includes(p.health)).length||0;
 function select(value:Resource|Project){setSelected(value.id);}
 return <div className="world-page"><Heading title="Your infrastructure. Alive." subtitle="Explore projects, trace connections, find what needs attention."><div className="world-stats"><div><strong>{data?.projects.length??'—'}</strong><small>projects</small></div><div><strong>{data?count:'—'}</strong><small>services</small></div><div><strong className={attention?'coral':''}>{data?attention:'—'}</strong><small>need attention</small></div><div className="host-stat"><Cpu size={13}/><strong>{formatPercent(data?.host_metrics?.cpu_percent)}</strong><small>CPU</small></div><div className="host-stat"><MemoryStick size={13}/><strong>{formatPercent(data?.host_metrics?.memory_percent)}</strong><small>memory</small></div><div className="host-stat"><HardDrive size={13}/><strong>{formatPercent(data?.host_metrics?.disk_percent)}</strong><small>disk</small></div></div><button className="button subtle" onClick={()=>void refresh()} title="Refresh observations"><RefreshCw size={15}/><span>Refresh</span></button></Heading>
 {error&&<ErrorNotice message={error} retry={refresh}/>}{data?.stale&&<div className="notice"><Info size={15}/>{data.message||'Showing last known observations. Reconnecting to discovery.'}</div>}
 <div className="world-toolbar"><label className="search-field"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a project, service or domain" aria-label="Search infrastructure"/>{query&&<button className="icon-button" onClick={()=>setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label><select aria-label="Filter project" value={projectFilter} onChange={e=>setProjectFilter(e.target.value)}><option value="all">All projects</option>{data?.projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Filter health" value={health} onChange={e=>setHealth(e.target.value)}><option value="all">All states</option>{['HEALTHY','DEGRADED','UNHEALTHY','UNAVAILABLE','STOPPED','CHANGING'].map(v=><option key={v} value={v}>{label(v)}</option>)}</select><button className={'button toggle '+(domains?'on':'')} aria-pressed={domains} onClick={()=>setDomains(!domains)}><Globe2 size={15}/>Domains</button><button className={'button toggle network-toggle '+(networks?'on':'')} aria-pressed={networks} title="Show shared networks; these do not prove application dependencies" onClick={()=>setNetworks(!networks)}><Network size={15}/></button></div>
 <div className={'world-stage '+(selected?'with-inspector':'')}>
 {loading?<Loading/>:!projects.length?<Empty title={data?.projects.length?'No matching projects':'Your world is taking shape'}>{data?.projects.length?'Try a different search or filter.':data?.message||'Projects will appear when Dokploy discovery is connected.'}</Empty>:mode==='3d'?<SceneBoundary use2d={()=>setMode('2d')}><Scene projects={projects} connections={data?.connections||[]} selected={selected} onSelect={select} reset={reset} focus={focus} domains={domains} networks={networks}/></SceneBoundary>:<div className="flat-world">{projects.map(p=><section className={'project-island '+(selected===p.id?'selected':'')} key={p.id}><button className="project-title" onClick={()=>select(p)}><span><i className="tiny-orb"/><strong>{p.name}</strong><small>{p.environments.join(' / ')}</small></span><Status state={p.health}/></button><div className="flat-resources">{p.resources.map(r=><button key={r.id} onClick={()=>select(r)} className={selected===r.id?'selected':''}><Box size={18}/><span>{r.name}<small>{r.kind} · {r.environment}</small></span><Status state={r.health}/></button>)}{!p.resources.length&&<p className="muted">No services deployed.</p>}</div>{domains&&<div className="flat-domains">{p.resources.flatMap(r=>r.domains.map(d=><button key={r.id+d.url} onClick={()=>select(r)}><Globe2 size={12}/>{new URL(d.url).host}<ArrowRight size={12}/>{r.name}</button>))}</div>}{networks&&<div className="network-summary"><Network size={12}/>{[...new Set(p.resources.flatMap(r=>r.networks))].join(', ')||'No observed network memberships'}</div>}</section>)}</div>}
 {active&&selectedProject&&<aside className="inspector"><div className="inspector-head"><span className="eyebrow">{resource?label(resource.kind):'PROJECT'}</span><button className="icon-button" aria-label="Close inspector" onClick={()=>setSelected(null)}><X size={18}/></button></div><h2>{active.name}</h2><Status state={active.health}/><p className="inspector-context">{resource?`${selectedProject.name} / ${resource.environment}`:`${selectedProject.resources.length} services across ${selectedProject.environments.length} environments`}</p><button className="button focus-button" onClick={()=>{setFocus(active.id);setReset(v=>v+1);}}><Focus size={14}/>Focus in world</button>
 {resource?<><div className="detail-section"><h3>Runtime</h3><dl><dt>Deployment</dt><dd>{label(resource.deployment_state)}</dd><dt>Replicas</dt><dd>{resource.replicas?`${resource.replicas.running}${resource.replicas.desired===null?' observed':` / ${resource.replicas.desired}`}`:resource.runtime_state}</dd><dt>Coverage</dt><dd>{data?.coverage??0}%</dd><dt>Observed</dt><dd>{timeAgo(resource.observed_at)}</dd></dl></div><TelemetryPanel resource={resource}/>{resource.repository&&<div className="detail-section"><h3>Deployment source</h3><dl><dt>Repository</dt><dd>{resource.owner}/{resource.repository}</dd><dt>Branch</dt><dd><GitBranch size={12}/>{resource.branch||'—'}</dd><dt>Build</dt><dd>{resource.build_type||'—'} · {resource.dockerfile||resource.build_path||'/'}</dd><dt>Auto deploy</dt><dd>{resource.auto_deploy?'Enabled':'Disabled'}</dd></dl>{resource.recent_deployments[0]&&<div className="latest-deploy"><Clock3 size={13}/><span>{resource.recent_deployments[0].title}<small>{resource.recent_deployments[0].commit?.slice(0,8)||resource.recent_deployments[0].status} · {timeAgo(resource.recent_deployments[0].finished_at)}</small></span></div>}</div>}<div className="detail-section"><h3>Domains & routes</h3>{resource.domains.length?resource.domains.map(d=><div className="domain-detail" key={d.url}><External href={d.url}>{new URL(d.url).host}</External><Status state={d.state}/><p>{d.message}</p><small>{timeAgo(d.checked_at)}{d.latency_ms!==null?` · ${d.latency_ms} ms`:''}</small><div className="route-path"><Globe2 size={13}/><span>Domain</span><ArrowRight size={12}/><Box size={13}/><span>{resource.name}</span></div>{d.incident_id&&<Link className="button danger" href={'/incidents/'+d.incident_id}>View incident <ArrowRight size={14}/></Link>}</div>):<p className="muted">No public domain configured.</p>}</div><div className="detail-section"><h3>Connections</h3>{resource.networks.map(n=><div className="network-row" key={n}><Network size={13}/>{n}</div>)}{!resource.networks.length&&<p className="muted">No network membership observed.</p>}<small>Network membership indicates shared connectivity, not a proven dependency.</small></div><div className="detail-section evidence-list"><h3>Evidence</h3>{resource.evidence.map(item=><div key={item.source}><i className={item.state}/><span>{label(item.source)}<small>{item.state} · {timeAgo(item.observed_at)}</small></span></div>)}</div></>:<div className="detail-section"><h3>Services</h3>{selectedProject.resources.map(r=><button className="inspector-service" key={r.id} onClick={()=>select(r)}><Box size={14}/><span>{r.name}</span><Status state={r.health}/><ChevronRight size={13}/></button>)}</div>}
 <Link className="button primary" href={'/agent?resource='+encodeURIComponent(active.name+' ('+active.id+')') }><Sparkles size={15}/>Ask Agent <ArrowRight size={14}/></Link><div className="inspector-note"><Info size={13}/><span>Observed infrastructure. Health checks run from the NightWatch host.</span></div></aside>}
 </div><div className="world-footer"><div className="legend">{['HEALTHY','DEGRADED','UNHEALTHY','UNAVAILABLE'].map(s=><Status key={s} state={s}/>)}</div><div className="world-controls"><span className="orbit-hint"><MousePointer2 size={13}/>Orbit / Pan</span><button className="button" onClick={()=>{setFocus(null);setReset(v=>v+1);}}><Maximize size={14}/>Fit view</button><button className="icon-button" aria-label="Reset world" onClick={()=>{setQuery('');setHealth('all');setProjectFilter('all');setSelected(null);setFocus(null);setReset(v=>v+1);}}><RotateCcw size={15}/></button><button className="button" onClick={()=>setMode(mode==='3d'?'2d':'3d')}><Layers3 size={15}/>{mode==='3d'?'2D view':'3D world'}</button></div><small className="world-updated">{timeAgo(data?.generated_at)}</small></div>
 </div>;
}
