'use client';
import {Suspense,useMemo,useRef,useEffect} from 'react';
import {Canvas,useThree} from '@react-three/fiber';
import {OrbitControls,Html,Line,RoundedBox,ContactShadows} from '@react-three/drei';
import * as THREE from 'three';
import type {OrbitControls as OrbitType} from 'three-stdlib';
import type {Project,Resource} from '@/lib/types';
import {color} from '@/lib/client';
export function islandPosition(index:number,count:number):[number,number,number]{const cols=Math.min(3,Math.ceil(Math.sqrt(count))),rows=Math.ceil(count/cols);return [(index%cols-(cols-1)/2)*10,0,(Math.floor(index/cols)-(rows-1)/2)*9];}
function random(seed:number){return ()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};}
function Rock({seed}:{seed:number}){const geometry=useMemo(()=>{const rand=random(seed+1);const geom=new THREE.CylinderGeometry(3.8,1.5,2.6,9,2);const pos=geom.attributes.position;for(let i=0;i<pos.count;i++){const y=pos.getY(i);pos.setXYZ(i,pos.getX(i)+(rand()-.5)*.48,y+(rand()-.5)*.5,pos.getZ(i)+(rand()-.5)*.48);}geom.computeVertexNormals();return geom;},[seed]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <mesh geometry={geometry} position={[0,-1.65,0]} castShadow receiveShadow><meshStandardMaterial color="#263532" roughness={.94} flatShading/></mesh>;}
function Tree({position,scale=1}:{position:[number,number,number];scale?:number}){return <group position={position} scale={scale}><mesh position={[0,.3,0]}><cylinderGeometry args={[.07,.11,.6,5]}/><meshStandardMaterial color="#5b5b49"/></mesh><mesh position={[0,.83,0]} castShadow><coneGeometry args={[.4,1.15,6]}/><meshStandardMaterial color="#3d6857" roughness={.92} flatShading/></mesh><mesh position={[0,1.22,0]}><coneGeometry args={[.3,.8,5]}/><meshStandardMaterial color="#517d60" roughness={.95}/></mesh></group>;}
function Building({resource,index,onSelect,selected}:{resource:Resource;index:number;onSelect:(r:Resource)=>void;selected:boolean}){const db=['postgres','mysql','mariadb','mongo','redis','libsql'].includes(resource.kind);const hue=color(resource.health);const height=db?1.2:1.05+(index%3)*.3;return <group onClick={e=>{e.stopPropagation();onSelect(resource);}} onPointerOver={e=>{e.stopPropagation();document.body.style.cursor='pointer';}} onPointerOut={()=>document.body.style.cursor='auto'}>
 {db?<><mesh position={[0,height/2+.15,0]} castShadow><cylinderGeometry args={[.52,.52,height,20]}/><meshStandardMaterial color={selected?'#809c94':'#657575'} metalness={.5} roughness={.3}/></mesh>{[.25,.7,1.15].map(y=><mesh key={y} position={[0,y,0]}><cylinderGeometry args={[.54,.54,.045,20]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={.4}/></mesh>)}</>:<><RoundedBox args={[1.1,height,1.15]} position={[0,height/2+.15,0]} radius={.04} castShadow receiveShadow><meshStandardMaterial color={selected?'#a7b7b5':'#78878b'} metalness={.25} roughness={.55}/></RoundedBox><mesh position={[0,height+.18,0]} castShadow><boxGeometry args={[1.2,.1,1.25]}/><meshStandardMaterial color="#a8b2b1"/></mesh><mesh position={[.1,height+.32,.12]}><boxGeometry args={[.4,.22,.5]}/><meshStandardMaterial color="#475357"/></mesh>{[0,1,2].map(row=><group key={row}>{[-.34,0,.34].map(x=><mesh key={x} position={[x,.37+row*.28,.581]}><planeGeometry args={[.15,.15]}/><meshStandardMaterial color={hue} emissive={hue} emissiveIntensity={selected?.8:.28}/></mesh>)}</group>)}</>}
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.08,0]}><ringGeometry args={[.79,.83,32]}/><meshBasicMaterial color={selected?'#d6ffe9':hue} transparent opacity={selected?1:.4}/></mesh>
 </group>;}
function Island({project,index,count,selected,onSelect,domains}:{project:Project;index:number;count:number;selected:string|null;onSelect:(r:Resource|Project)=>void;domains:boolean}){const position=islandPosition(index,count);const seed=project.id.split('').reduce((a,c)=>a+c.charCodeAt(0),0);const trees=useMemo(()=>{const rand=random(seed);return Array.from({length:8},(_,i)=>{const angle=i/8*Math.PI*2;return {position:[Math.cos(angle)*3.08,.1,Math.sin(angle)*3.08] as [number,number,number],scale:.45+rand()*.4};});},[seed]);const resources=project.resources.slice(0,8);return <group position={position}>
 <Rock seed={seed}/><mesh position={[0,-.12,0]} receiveShadow><cylinderGeometry args={[3.72,3.82,.38,9]}/><meshStandardMaterial color="#506057" roughness={.95}/></mesh><mesh position={[0,-.36,0]}><cylinderGeometry args={[3.81,3.81,.04,9]}/><meshStandardMaterial color={color(project.health)} emissive={color(project.health)} emissiveIntensity={.24}/></mesh>
 <mesh rotation={[-Math.PI/2,0,0]} position={[0,.079,0]} receiveShadow><planeGeometry args={[5.3,.62]}/><meshStandardMaterial color="#89928a" roughness={.9}/></mesh><mesh rotation={[-Math.PI/2,0,Math.PI/2]} position={[0,.08,0]} receiveShadow><planeGeometry args={[5.3,.5]}/><meshStandardMaterial color="#89928a" roughness={.9}/></mesh>
 {trees.map((t,i)=><Tree key={i} {...t}/>)}
 {resources.map((r,i)=>{const cols=Math.min(3,resources.length),x=(i%cols-(cols-1)/2)*1.5,z=(Math.floor(i/cols)-.5)*1.8;return <group key={r.id} position={[x,0,z]}><Building resource={r} index={i} selected={selected===r.id} onSelect={onSelect}/>{selected===r.id&&<Html position={[0,2,0]} center distanceFactor={30} zIndexRange={[20,0]}><button className="building-label" onClick={()=>onSelect(r)}>{r.name}</button></Html>}</group>;})}
 {!resources.length&&<mesh position={[0,.3,0]}><boxGeometry args={[1.2,.3,1.2]}/><meshStandardMaterial color="#6f7a78" wireframe/></mesh>}
 <Html center position={[0,2.6,-1.8]} distanceFactor={32} zIndexRange={[15,0]}><button className={'island-label '+(selected===project.id?'selected':'')} onClick={()=>onSelect(project)}><i style={{background:color(project.health)}}/><span>{project.name}<small>{project.resources.length} {project.resources.length===1?'service':'services'}{domains&&project.resources.flatMap(r=>r.domains).length?` · ${project.resources.flatMap(r=>r.domains).length} domains`:''}</small></span></button></Html>
 {domains&&project.resources.some(r=>r.domains.length>0)&&<group position={[2.8,0,.7]}><mesh rotation={[-Math.PI/2,0,0]} position={[0,.11,0]}><torusGeometry args={[.4,.045,8,32]}/><meshStandardMaterial color={color(project.health)} emissive={color(project.health)} emissiveIntensity={.7}/></mesh><Line points={[[0,.2,0],[-.5,.8,-.3],[-1.3,.45,-.7]]} color={color(project.health)} lineWidth={1.3} transparent opacity={.7}/></group>}
 </group>;}
function Camera({reset,focus,projects}:{reset:number;focus:string|null;projects:Project[]}){const ref=useRef<OrbitType>(null);const{camera,invalidate}=useThree();const index=projects.findIndex(p=>p.id===focus||p.resources.some(r=>r.id===focus));const count=projects.length;useEffect(()=>{const target=index>=0?islandPosition(index,count):[0,0,0];const distance=index>=0?12:Math.max(21,Math.sqrt(count)*9);camera.position.set(target[0]+distance*.7,distance*.85,target[2]+distance);ref.current?.target.set(target[0],0,target[2]);ref.current?.update();invalidate();},[reset,focus,index,count,camera,invalidate]);return <OrbitControls ref={ref} makeDefault enableDamping dampingFactor={.12} minDistance={6} maxDistance={85} maxPolarAngle={Math.PI/2.2} minPolarAngle={.15}/>;}
export default function WorldScene({projects,selected,onSelect,reset,focus,domains,networks}:{projects:Project[];selected:string|null;onSelect:(r:Resource|Project)=>void;reset:number;focus:string|null;domains:boolean;networks:boolean}){const shared=useMemo(()=>{const edges:{from:number;to:number;name:string}[]=[];for(let a=0;a<projects.length;a++)for(let b=a+1;b<projects.length;b++){const left=new Set(projects[a].resources.flatMap(r=>r.networks));const common=projects[b].resources.flatMap(r=>r.networks).find(n=>left.has(n));if(common)edges.push({from:a,to:b,name:common});}return edges;},[projects]);return <Canvas shadows dpr={[1,1.5]} frameloop="demand" camera={{position:[20,25,32],fov:42,near:.1,far:180}} gl={{antialias:true,alpha:true,powerPreference:'high-performance'}} onCreated={({gl})=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.3;}}><fog attach="fog" args={['#101719',45,110]}/><ambientLight intensity={.65}/><hemisphereLight args={['#c5e3ec','#162b1c',1.2]}/><directionalLight position={[10,20,10]} intensity={2.5} castShadow shadow-mapSize={[2048,2048]} shadow-camera-left={-30} shadow-camera-right={30} shadow-camera-top={30} shadow-camera-bottom={-30} shadow-bias={-.001}/><directionalLight position={[-15,10,-15]} color="#78b1ac" intensity={1.3}/><Suspense fallback={null}>{projects.map((project,i)=><Island key={project.id} project={project} index={i} count={projects.length} selected={selected} onSelect={onSelect} domains={domains}/>)}{networks&&shared.map(e=>{const a=islandPosition(e.from,projects.length),b=islandPosition(e.to,projects.length);return <Line key={e.from+':'+e.to} points={[a,[(a[0]+b[0])/2,-.2,(a[2]+b[2])/2],b]} color="#8dc8c2" lineWidth={1} dashed dashSize={.3} gapSize={.2} transparent opacity={.4}/>;})}<ContactShadows position={[0,-4,0]} opacity={.25} scale={90} blur={3} far={12} resolution={256} frames={1}/></Suspense><Camera reset={reset} focus={focus} projects={projects}/></Canvas>;}
