export const WALKTHROUGH = 'https://drive.google.com/file/d/1TDCbsb495BiY4YK6dNxIdD-WkLR4p85g/view?usp=sharing';

export const chapters = [
  { id: 'observe', label: 'Observe', title: 'A running container.\nA broken experience.', description: 'A service can be running while its public route is failing. NightWatch keeps those observations separate, so the real problem stays visible.', lines: [['Public endpoint', 'HTTP 502'], ['Docker container', 'Running'], ['Evidence status', 'Needs investigation']], tone: 'coral' },
  { id: 'investigate', label: 'Investigate', title: 'Five perspectives.\nOne clearer picture.', description: 'Configuration, container identity, telemetry, routing, and HTTP checks come together around the same resource. Every conclusion has evidence behind it.', lines: [['Dokploy', 'Configured service'], ['Docker', 'Listening on :8000'], ['Beszel', 'Runtime observation'], ['Traefik', 'Targeting :9999'], ['HTTP probe', 'Internal 200 · public 502']], tone: 'amber' },
  { id: 'understand', label: 'Understand', title: 'Find the mismatch.\nShow the reasoning.', description: 'The container listens on port 8000. Its route points to 9999. A focused hypothesis explains the failure and cites the observations that support it.', lines: [['Observed port', '8000'], ['Route target', '9999'], ['Hypothesis', 'Upstream port mismatch']], tone: 'amber' },
  { id: 'review', label: 'Review', title: 'The agent proposes.\nYou stay in control.', description: 'A change becomes an exact, versioned plan with a target and a reason. The operator reviews it; the application rechecks the target before executing.', lines: [['Proposed change', '9999 → 8000'], ['Approval', 'Exact plan version'], ['Before execution', 'Revalidate target state']], tone: 'mint' },
  { id: 'verify', label: 'Verify', title: 'Accepted is a step.\nVerified is evidence.', description: 'Execution and recovery are different events. Separate checks inspect the running service, route configuration, internal health, and public response.', lines: [['Management operation', 'Recorded separately'], ['Public endpoint', 'Illustrative HTTP 200'], ['Outcome', 'Verification preserved']], tone: 'mint' },
] as const;

export const capabilities = [
  { id: 'world', label: 'World & telemetry', title: 'The whole picture, in a world you can explore.', description: 'Project islands, service buildings, domain gateways, and network context make the environment tangible. Switch to 2D when dense information needs a simpler view.', image: '/showcase/world-3d.webp', alt: 'Recorded NightWatch infrastructure world with project islands and service connections', features: ['Interactive 3D and practical 2D views', 'Dokploy, Docker, and Beszel reconciliation', 'Host and container telemetry', 'Fresh, stale, and unavailable evidence', 'Realtime updates with polling fallback'] },
  { id: 'incidents', label: 'Investigation & incidents', title: 'Every incident has a story. Keep the evidence.', description: 'Follow affected resources, observations, hypotheses, actions, and recovery through a dated timeline. Inspect the records behind a conclusion instead of taking its word for it.', image: '/showcase/incident-timeline.webp', alt: 'Recorded NightWatch incident timeline showing failure observations and recovery checks', features: ['Affected resources and exact event dates', 'Evidence-linked hypotheses', 'Bounded manual investigation', 'Raw recorded details and citations', 'Separate execution and verification records'] },
  { id: 'agent', label: 'Agent & approvals', title: 'A second set of eyes. With boundaries.', description: 'Ask a question in plain language. The agent inspects typed evidence sources, preserves conversations, and prepares reviewable actions while policy and execution remain in deterministic code.', image: '/showcase/agent-investigation.webp', alt: 'Recorded NightWatch agent investigation with evidence citations', features: ['Persistent conversations and streamed activity', 'Typed tools instead of an unrestricted shell', 'Exact-version human approval', 'Target revalidation and stale-plan rejection', 'Server-held credentials and secret filtering'] },
  { id: 'deployments', label: 'Deployments & operations', title: 'From “host this” to a reviewable operation.', description: 'Repository, branch, Dockerfile, port, domain, and target become a persisted deployment plan. Supported Dokploy operations and reports share the same operational history.', image: '/showcase/agent-deployment.webp', alt: 'Recorded NightWatch deployment plan and independently checked HTTP response', features: ['Natural language to deployment plans', 'Registered start, stop, deploy, and redeploy workflows', 'Approval, execution, verification, and retry states', 'Operational reports and CSV export', 'Management results distinct from public health'] },
] as const;

export const engineeringDetails = [
  { title: 'A world built from evidence', text: 'Dokploy inventory, Docker identity, Beszel observations, route configuration, and HTTP probes are reconciled into one world snapshot. A shared network is context; it does not prove traffic direction or an application dependency.' },
  { title: 'Plans that remember what was approved', text: 'Mutation plans preserve the target, parameters, policy reason, relevant observed state, and exact version. The application re-reads the target before execution and rejects a plan when the approved state has changed.' },
  { title: 'Two model roles, bounded responsibilities', text: 'The operator agent uses gpt-5.6-luna through the Codex app-server. A separate manual investigator uses gpt-5.4-mini with a three-tool-call ceiling, output limits, redacted context, and a timeout. Continuous monitoring does not automatically invoke either model.' },
  { title: 'Real infrastructure has awkward edges', text: 'A configured service may not have a running replica. A management API may accept a change while the endpoint still fails. NightWatch records lifecycle-specific behavior, execution results, stale telemetry, unavailable data, and outstanding verification without collapsing them into one success state.' },
  { title: 'Persistence and service boundaries', text: 'FastAPI owns integration access, evidence, policy, and execution. SQLite stores incidents, observations, plans, approvals, conversations, and verification through SQLAlchemy and Alembic. Next.js validates signed HTTP-only operator sessions and proxies allowlisted routes. A separate restricted Docker observer supplies runtime evidence.' },
  { title: 'The boundaries of this build', text: 'NightWatch is a private, single-operator control plane. It does not claim fleet administration, organization-wide RBAC, unrestricted autonomous access, universal rollback, or benchmarked uptime and repair speed. Database and volume deletion are not exposed as agent operations.' },
] as const;
